name: DevSecOps CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build || echo "Build not required"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test || echo "No tests defined"

  sca:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run SCA scan (npm audit)
        run: npm audit --json > npm-audit-report.json

      - name: Upload audit report
        uses: actions/upload-artifact@v4
        with:
          name: npm-audit-report
          path: npm-audit-report.json

  sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep (SAST)
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/owasp-top-ten"
          generateSarif: true

      - name: Upload Semgrep report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep.sarif

  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install TruffleHog
        run: pip install trufflehog

      - name: Run TruffleHog secrets scan
        run: trufflehog file://. --json | tee trufflehog-report.json

      - name: Upload TruffleHog report
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-report
          path: trufflehog-report.json

  dast:
    runs-on: ubuntu-latest
    steps:
      - name: Start Juice Shop container
        run: docker run -d -p 3000:3000 --name juice bkimminich/juice-shop

      - name: Wait for container to start
        run: sleep 20

      - name: Run OWASP ZAP scan
        run: docker run --network host -v ${{ github.workspace }}:/zap/wrk owasp/zap2docker-stable zap-baseline.py -t http://localhost:3000 -J zap-report.json || true

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.json

  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t juice-shop .

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: juice-shop
          severity: HIGH,CRITICAL
          format: table
          output: trivy-report.txt

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt

  docker-push:
    needs: [trivy]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_USER }}/juice-shop:latest .

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USER }}/juice-shop:latest
